name: Docker Images CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, converter, gateway, notification] # Add all service names here
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=kescfko/${{ matrix.service }}
        SERVICE_PATH=src/${{ matrix.service }}
        TAG=$(date +%Y%m%d%H%M%S)
        
        docker build $SERVICE_PATH --file $SERVICE_PATH/Dockerfile --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$TAG
